name: Terraform Plan Action
description: composite action for terraform plan
inputs:
  directory:
    description: Folder terraform files are stored
    required: true
  AWS_ACCESS_KEY_ID:
    description: Access key for AWS account
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: Secret key for AWS account
    required: true
  aws-region:
    description: Required Region
    required: true
    default: eu-central-1
  terraform_version:
    description: Current version of Terraform
    required: true
    default: 1.5.7
  
runs:
  using: composite
  steps:
  - name: Run script file 
    run: |
        chmod +x scripts.sh
        ./scripts.sh
    shell: bash

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v2
    with:
        terraform_version: ${{ inputs.terraform_version }}

  - name: Configure AWS 
    uses: aws-actions/configure-aws-credentials@v2
    env:
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws-region }}  


    