name: Terraform Apply
on:
  workflow_dispatch:
    branches:
      - main
env:
  terraformversion: 1.5.7
  aws-region: eu-central-1
  aws-s3-bucket: bshorg-ss-bucket-check
  dynamodb_name: bshorg-dynamodb-table-check
  arn_role: arn:aws:iam::115233747096:role/test-github-oidc

jobs:
  Plan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Terraform Plan
        uses: ./.github/apply
        with:
          terraform_version: ${{ env.terraformversion }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID || inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY || inputs.aws-secret-access-key }}   
          aws-region: ${{ env.aws-region || inputs.aws-region }} 
          aws-s3-bucket: ${{ env.aws-s3-bucket || inputs.aws-s3-bucket }}
          arn_role: ${{env.arn_role || inputs.arn_role }}
      - name: Bash cmd
        run: echo 0
        