name: Manual and Automated Workflow

on:
  push:
    branches:
      - main

jobs:
  manual_approval:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Manual Approval Step
        id: manual_approval
        run: |
          echo "Manual approval step"
          echo "::set-output name=approved::true"  # Set an output indicating approval

  automated_steps:
    needs: manual_approval
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Automated Step 1
        if: needs.manual_approval.outputs.approved == 'true'  # Check for manual approval
        run: echo "Running Automated Step 1"

      - name: Automated Step 2
        if: needs.manual_approval.outputs.approved == 'true'
        run: echo "Running Automated Step 2"
