name: Manual Approval Example

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build and Test
        run: echo "Building and testing the application"
      
      - name: Deploy to Production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "Deploying to production"

      - name: Manual Approval
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: approval
        run: echo "::set-output name=approved::true"

  notify:
    needs: deploy
    if: needs.deploy.outputs.approved == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Notify Success
        run: echo "Deployment approved and successful"
