name: Terraform Execution

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

# permissions:
#   contents: read
#   security-events: write
#   actions: read

jobs:
  Codecheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkov GitHub Action
      uses: bridgecrewio/checkov-action@v12
      with:
        output_format: cli,sarif
        output_file_path: console,results.sarif
      continue-on-error: true

    - name: Upload Log as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: main.tf
        path: .github/workflows
    - name: Terrascan GitHub Action
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: false

    - name: deploy part
      run: |
        #!/bin/bash
        echo 999
        ls .github/workflows

  # Terraform:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - 
