name: Terraform Execution

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Codecheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkov GitHub Action
      run: |
        apt-get update -y
        apt install python3-pip -y
        pip3 install checkov -y
        checkov -d ./
      continue-on-error: true

    - name: Upload Log as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: results.sarif
        path: ./
    - name: Terrascan GitHub Action
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: false
