name: Terraform Execution
on:
  push:
    branches:
      - main
env:
  bucket_name: bshorg-ss-bucket-check
  dynamodb_name: bshorg-dynamodb-table-check
jobs:
  Codecheck:
    runs-on: ubuntu-latest
    container:
      image: xalt/quality_management:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test docker image
      run: |
        terraform --version
        checkov --version
        echo 1