name: Terraform Execution

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Codecheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Checkov GitHub Action
      run: |
        sudo apt-get update -y
        sudo apt install python3-pip 
        sudo pip3 install checkov 
        checkov -d ./ > checkov.log
      continue-on-error: true
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v2
      with:
          bucket_name: ${{ secrets.AWS_BUCKET_NAME }}
    - name: Upload Log as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: checkov log
        path: ./checkov.log
    - name: condition 
      if: bucket_name != 'Windows'
      run: echo "The operating system on the runner is not Windows, it's $RUNNER_OS."
