name: Terraform Plan
on:
  push:
    branches:
      - main
env:
  terraformversion: 1.5.7
  region: eu-central-1

jobs:
  Plan:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Plan
        uses: ./.github/actions/plan/action.yml@main
        with:
          terraform-version: ${{ env.terraformversion }}
          aws-access-key-id: ${{ secrets.aws-access-key-id}}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ env.region }}
    