name: Terraform Execution
on:
  push:
    branches:
      - main
env:
  bucket_name: bshorg-ss-bucket-check
  dynamodb_name: bshorg-dynamodb-table-check
jobs:
  Codecheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Run script file
      run: |
        chmod +x scripts.sh
        ./scripts.sh
      shell: bash