on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./.github/actions/make
        with:
          who-to-greet: 'Mona the Octocat'

      - name: Checkov GitHub Action
        run: |
          checkov -d ./ > checkov.log
        continue-on-error: true
      
