name: Terraform Plan
on:
  push:
    branches:
      - main
env:
  terraformversion: 1.5.7
  
jobs:
  Plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Terraform Plan
        uses: ./.github/actions
        with:
          terraform_version: ${{ env.terraformversion }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID || inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY || inputs.aws-secret-access-key }}    